### ISSUE TITLE
在微信开发者工具不支持getcontext（‘webgl’）

### ISSUE THREAD

**Issue by zhuhang4** [skyfish-qc/pixi-miniprogram#1]
更新到最新版本微信开发者工具（1.03.2005140）

按案例接入，报错
Canvas: current node only supports 2d context

将‘webgl’修改为‘2d’
报错Cannot set property 'fillRect' of undefined

**Comment by skyfish-qc** [comment]
我更新到最新版的微信开发者工具可以运行的，你的代码发一下看看？

**Comment by zhuhang4** [comment]
> 我更新到最新版的微信开发者工具可以运行的，你的代码发一下看看？

已经解决了，是我的问题，wxml里canvas的type选的2d而非webgl。谢谢您的回复！
