### ISSUE TITLE
PIXI.animate.Scene()不生效

### ISSUE THREAD

**Issue by binglww** [skyfish-qc/pixi-miniprogram#10]
我在使用 PixiAnimate.zxp 插件把flash导出后，放在小程序里使用，在ios下面是可以正常渲染显示，但是安卓不行没有任何显示，也没有报错，经测试是这段代码在安卓下不生效

  var scene  = new  PIXI.animate.Scene( {
                        view: canvas,
                        width: stageWidth,
                        height: stageHeight,
                        backgroundColor: 0xffffff,
                        antialias: true
                    });

**Comment by skyfish-qc** [comment]
PIXI.animate.Scene这个对象是继承PIXI.Application的，你直接用PIXI.Application能显示么？另外如果new Scene了，就不能再使用new Application或者PIXI.autoDetectRenderer这个会重复

**Comment by binglww** [comment]
> PIXI.animate.Scene这个对象是继承PIXI.Application的，你直接用PIXI.Application能显示么？另外如果new Scene了，就不能再使用new Application或者PIXI.autoDetectRenderer这个会重复

感谢回复，使用PIXI.Application 不能显示，new Scene 后，也没有使用PIXI.autoDetectRendere，很奇怪的是模拟器和ios可以正常显示。检查安卓也没有报错，我弄了代码片段，可以麻烦你看一下吗[pixi-animate](https://developers.weixin.qq.com/s/RFZzVbmN7wqv)

**Comment by skyfish-qc** [comment]
> > PIXI.animate.Scene这个对象是继承PIXI.Application的，你直接用PIXI.Application能显示么？另外如果new Scene了，就不能再使用new Application或者PIXI.autoDetectRenderer这个会重复
> 
> 感谢回复，使用PIXI.Application 不能显示，new Scene 后，也没有使用PIXI.autoDetectRendere，很奇怪的是模拟器和ios可以正常显示。检查安卓也没有报错，我弄了代码片段，可以麻烦你看一下吗[pixi-animate](https://developers.weixin.qq.com/s/RFZzVbmN7wqv)

这个问题我看了，是animate库在安卓下对图片类型判断有问题，已经修改animate库代码适配，你拉取examples里的animate库使用就可以正常显示了

**Comment by binglww** [comment]
> > > PIXI.animate.Scene这个对象是继承PIXI.Application的，你直接用PIXI.Application能显示么？另外如果new Scene了，就不能再使用new Application或者PIXI.autoDetectRenderer这个会重复
> > 
> > 
> > 感谢回复，使用PIXI.Application 不能显示，new Scene 后，也没有使用PIXI.autoDetectRendere，很奇怪的是模拟器和ios可以正常显示。检查安卓也没有报错，我弄了代码片段，可以麻烦你看一下吗[pixi-animate](https://developers.weixin.qq.com/s/RFZzVbmN7wqv)
> 
> 这个问题我看了，是animate库在安卓下对图片类型判断有问题，已经修改animate库代码适配，你拉取examples里的animate库使用就可以正常显示了

可以了，非常感谢[强]~~
