### ISSUE TITLE
有什么办法减小内存占用吗

### ISSUE THREAD

**Issue by binglww** [skyfish-qc/pixi-miniprogram#13]
我是animate做动画导出pixi版本，小程序引用了pixi-animate 、unsafeEval、pixi.miniprogram，但是小程序内存限制太小了，使用小程序中经常会提示内存不足，有时候整个微信直接闪退，我已经把unsafeEval、pixi-animate换成了较新的版本也做了压缩处理，但是并没有什么效果，不知道有没有其他办法能够减小内存的占用。

**Comment by skyfish-qc** [comment]
小程序内存确实太小，代码上要注意不能不停的创建Sprite，不用的资源要及时destroy，如果都做了处理，就只能是减少图片尺寸了，图片越大占内存越大。其它办法就想不到了。

**Comment by skyfish-qc** [comment]
每次进入小程序时候，都要清一下PIXI缓存，重新初始化页面，这样可以减少闪退概率。
