### ISSUE TITLE
uniform sampler2D 类型的变量 只能用uSampler，用其他命名就会出错

### ISSUE THREAD

**Issue by Suo-Ran** [skyfish-qc/pixi-miniprogram#14]
varying vec2 vTextureCoord;
uniform sampler2D uSampler;
uniform float amount;
 void main() {
	vec4 color = texture2D(uSampler, vTextureCoord);
	float average = (color.r + color.g + color.b) / 3.0;
	float mx = max(color.r, max(color.g, color.b));
	float amt = (mx - average) * (-amount * 3.0);
	color.rgb = mix(color.rgb, vec3(mx), amt);
	gl_FragColor = color;
}
这是我的代码，调整靓丽度的，

**Comment by skyfish-qc** [comment]
不是的，uSampler是默认的命名，这个不需要在uniform额外申明的。如果是其它命名，就需要在uniform申明变量，你可以看看例子的遮罩示例代码，那个masktex就是其它命名的

**Comment by skyfish-qc** [comment]
你如果是调整自身的纹理，那命名就是固定的uSampler，如果是调整从uniform引入的纹理，就随意命名。

**Comment by Suo-Ran** [comment]
> 你如果是调整自身的纹理，那命名就是固定的uSampler，如果是调整从uniform引入的纹理，就随意命名。

好的，多谢，我回头去尝试
