### ISSUE TITLE
添加MP3文件资源的时候会出现 Cannot set property 'crossOrigin' of undefined

### ISSUE THREAD

**Issue by nlb1466488** [skyfish-qc/pixi-miniprogram#15]
添加MP3文件资源的时候会出现
![image](https://user-images.githubusercontent.com/39716269/160362498-d9b680bc-0302-4c4a-ae75-c268c12cf8a4.png)

![image](https://user-images.githubusercontent.com/39716269/160362403-feb5c773-9ad0-4ba1-afda-f5ee4a52a033.png)

**Comment by skyfish-qc** [comment]
之前版本没有支持音频，现在已加上音频支持
