### ISSUE TITLE
模拟器出现canvas渲染在最顶层。设置z-index无效

### ISSUE THREAD

**Issue by flowers1225** [skyfish-qc/pixi-miniprogram#16]
canva的层级最顶层。设置定位 z-index无效。
测试使用原生同层渲染canvas上 可以覆盖view 换成pixijs 就不行了。
求解！

![image](https://user-images.githubusercontent.com/5829050/160887512-2442b660-f5aa-4125-8c09-68addc650053.png)
![image](https://user-images.githubusercontent.com/5829050/160887714-60da2494-809d-4fda-a0a5-c4d0d6992fe4.png)

模拟器版本： 2.19.2

**Comment by Suo-Ran** [comment]
这个好像是模拟器bug，我之前用原生webgl撸出来，也遇到这种问题，找半天也没找到咋解决，倒是真机正常
