### ISSUE TITLE
spine 可以升级一下 3.8 的库吗？

### ISSUE THREAD

**Issue by ado5** [skyfish-qc/pixi-miniprogram#17]
spine 使用 3.8 的编辑器导出的文件会报错，提示 WAServiceMainContext.js:2 Error: Slot not found: name， 请问可以升级一下吗？ 感谢!

**Comment by skyfish-qc** [comment]
3.8的spine库添加了，example/libs/pixi-spine-3.8.js，由于示例使用的是3.6的spine，就不修改示例代码了，使用时候按需引入对应的spine库就好。另外如果需要引起其它库，可以按照spine 3.8里面的注释说明添加头部，尾部代码就可以了。

**Comment by ado5** [comment]
正！ 大佬NB！
