### ISSUE TITLE
PC端调试白屏

### ISSUE THREAD

**Issue by TurkeyCoder** [skyfish-qc/pixi-miniprogram#24]
真机调试--PC端，白屏，无报错。

**Comment by skyfish-qc** [comment]
pc端小程序没有实现webgl的canvas，这个没有办法

**Comment by skyfish-qc** [comment]
由于PIXI使用了离屏canvas，但pc小程序不支持离屏canvas，https://developers.weixin.qq.com/community/develop/doc/000e0e58aa417810c57e5828e56400?highLine=createOffscreenCanvas%2520pc%25E7%25AB%25AF%2520null
可以看微信社区这个问题，目前要等官方解决才能支持pc端了
