### ISSUE TITLE
我创建了一个container 往里面加了些文字和图片，如何调用wx.canvasToTempFilePath把这个container导出成图片呢？

### ISSUE THREAD

**Issue by lence-wl** [skyfish-qc/pixi-miniprogram#25]

**Comment by skyfish-qc** [comment]
加了导出图片的代码示意。你可以看看example里面的例子。主要是初始化时候加上preserveDrawingBuffer:true，然后通过canvas导出base64数据，再转成buffer，然后保存成图片就可以了

**Comment by lence-wl** [comment]
好的 非常感谢

**Comment by lence-wl** [comment]
我测试了，安卓没问题，但是ios导出的是空白的透明图片，这个可能是哪里的问题呢？？ 
微信版本  8.0.33
ios 15.4.1

**Comment by skyfish-qc** [comment]
iOS我这边测试是正常的，你的微信库版本是多少？

**Comment by skyfish-qc** [comment]
你要在渲染后延时一点再导出

**Comment by lence-wl** [comment]
好的，我试了试 example 是可以的，我再看看我写的有什么区别，谢谢了

**Comment by lence-wl** [comment]
应该是基础库版本的问题吧，我用的是 2.30.2

**Comment by lence-wl** [comment]
微信兼容性的问题，我看到有相关帖子https://developers.weixin.qq.com/community/develop/doc/000c84be3845481a1029641e656400?_at=1581939859006
