### ISSUE TITLE
是否有计划更新pixijs版本？

### ISSUE THREAD

**Issue by mHalo** [skyfish-qc/pixi-miniprogram#28]
目前pixijs已经更新到v7版本，pixi-miniprogram是否有计划更新pixi到最新版本？

**Comment by skyfish-qc** [comment]
如果有需要，可以更新版本，目前版本应该能满足大部分需求的

**Comment by yoshi315** [comment]
同样请求更新到pixi 7，网上很多的pixi 5的doc都找不到了

**Comment by yoshi315** [comment]
如果比较麻烦，还请给与一些更新的提示

**Comment by yoshi315** [comment]
我先对比了您的pixi.js 5.2.1修改版，然后和pixi.js-5.2.1原版进行了对比，找到了修改点
之后拿着上述修改点，又到pixi.js-7.2.4里面进行了一番搜索，发现是可以进行修改的
就是不知道修改完了之后，还有没有什么其他坑

**Comment by skyfish-qc** [comment]
已更新到6.3.2
