### ISSUE TITLE
可以升级到"pixi.js": "6.3.2"吗？

### ISSUE THREAD

**Issue by ado5** [skyfish-qc/pixi-miniprogram#29]
可以升级到"pixi.js": "6.3.2"吗？ 有些API改变了， 这个版本相对稳定， 性能上也不错

**Comment by skyfish-qc** [comment]
可以

**Comment by mHalo** [comment]
> 可以升级到"pixi.js": "6.3.2"吗？ 有些API改变了， 这个版本相对稳定， 性能上也不错

我根据作者的源码增加了一个pixi.v-6.5.9版本的，如果需要的话可以尝试下，不过是自己项目里面用，所以没有做特别完善的测试，期待作者的更新哈~

https://github.com/mHalo/pixi-miniprogram/tree/v6

**Comment by skyfish-qc** [comment]
已更新到6.3.2
