### ISSUE TITLE
example下的文件在电脑模拟器和安卓都没问题，唯独ios下不显示

### ISSUE THREAD

**Issue by cailven** [skyfish-qc/pixi-miniprogram#3]
example下的文件在电脑模拟器和安卓都没问题，唯独ios下不显示，难道是还没有适配好ios吗？测试机型iphone11,ios13.7，微信7。0.15

**Comment by skyfish-qc** [comment]
ios可以运行的，估计是图片没加载出来，因为使用的是GitHub的图片资源

**Comment by cailven** [comment]
> ios可以运行的，估计是图片没加载出来，因为使用的是GitHub的图片资源

我把你的域名加到小程序白名单里也试过了还是不行，另外也把你的资源下载后传到自己服务器也试过。

**Comment by skyfish-qc** [comment]
你可以在ios那里打开调试台看看有没有报错输出，这个已经小程序上线的了，你可以搜一下 随身小阅读 这个小程序，就是用的这个库的

**Comment by cailven** [comment]
ios打开调试台没有报错，随身小阅读我手机上可以打开。但不清楚哪个部分是pixi做的，看到的就一个书架里面打开txt电子书而已，不清楚为啥用pixi。我再多试试吧。谢谢啦

**Comment by skyfish-qc** [comment]
那个整个小程序都是PIXI的，所有界面都是的

**Comment by cailven** [comment]
> 那个整个小程序都是PIXI的，所有界面都是的

谢谢，向你学习中，我看了你src里的源码基本上和小程序官网给threejs-miniprogram做的适配方法差不多，我最近也在使用同样的方法来建构createJs这套库在小程序中的适配。要考虑的东西确实很多。

除此之外，我刚刚也试着把你的这个pixi库放到阿里小程序中运行了下，因为阿里小程序有自己的pixi插件，使用了你的spin改写还是有很多问题，我还在改写中。之后有进展跟你分享。谢谢啦

**Comment by cailven** [comment]
![1c283066120ecdc16739609072c70d3](https://user-images.githubusercontent.com/4739001/94231213-1f7faf80-ff36-11ea-858c-a3ff41b5b359.jpg)

**Comment by cailven** [comment]
![Uploading 1c283066120ecdc16739609072c70d3.jpg…]()

**Comment by cailven** [comment]
![1c283066120ecdc16739609072c70d3](https://user-images.githubusercontent.com/4739001/94235428-227e9e00-ff3e-11ea-9914-0c2a5cf688ca.jpg)

**Comment by skyfish-qc** [comment]
你这个字体文件看起来没有加载

**Comment by cailven** [comment]
> 你这个字体文件看起来没有加载

没错，确实是加载的问题，我把字体都注释掉也不行，貌似外部加载的文件都报错，我再试试。

**Comment by skyfish-qc** [comment]
bimapFont字体需要用fnt格式的，放到服务器上加载，不能放本地加载

**Comment by skyfish-qc** [comment]
新版本可以使用系统字体，不再局限于bitmapFont
