### ISSUE TITLE
有木有兴趣加入Live2d？

### ISSUE THREAD

**Issue by cacard** [skyfish-qc/pixi-miniprogram#36]
1，pixi.js运行到miniprogram，见：https://github.com/skyfish-qc/pixi-miniprogram
2，把live2d运行到pixi.js：https://github.com/guansss/pixi-live2d-display 
3，可否结合二者？——即：将live2d(Web）适配到pixi.js，再适配到微信小程序。
4，还有个项目是直接将live2d运行在小程序：https://github.com/zhanghu11/live2d-wx

**Comment by skyfish-qc** [comment]
加上了
