### ISSUE TITLE
希望项目主把pixi-animate整合进去吧

### ISSUE THREAD

**Issue by cailven** [skyfish-qc/pixi-miniprogram#4]
整合pixi-animate主要是因为需要flash导出动画数据，我根据spin的方法试了几次发现还是无法正常运行，如果项目主有时间的话麻烦帮忙整合下吧，谢啦。

**Comment by skyfish-qc** [comment]
pixi-animate库已添加，版本为最新的2.0.0.rc5

**Comment by cailven** [comment]
太感谢了，我看到了。谢谢

**Comment by cailven** [comment]
我试了下，把flash导出的文件放进去适配还是不行，看来还得继续魔改一下。

**Comment by skyfish-qc** [comment]
如果是想使用flash导出的动画，可以使用createJs-miniprogram这个项目的

**Comment by cailven** [comment]
> 如果是想使用flash导出的动画，可以使用createJs-miniprogram这个项目的

太感谢了。你还特地做了一个，非常感谢
