### ISSUE TITLE
在手机上打开报错

### ISSUE THREAD

**Issue by hello-laozhang** [skyfish-qc/pixi-miniprogram#40]
显示没有Intl
![Uploading 微信图片_20240711101105.jpg…]()

**Comment by hello-laozhang** [comment]
![微信图片_20240711101105](https://github.com/skyfish-qc/pixi-miniprogram/assets/44487132/92ce434f-5b60-4616-b5ab-b562acda2ef4)

**Comment by skyfish-qc** [comment]
你需要使用V6版本的库，v7以上的pixi库使用了intl函数，是小程序不支持的。V6,V5的正常。另外，6.3.2版本里面的example里面的libs文件夹没有更新到pixi库，请在dist里面复制过去覆盖使用

**Comment by skyfish-qc** [comment]
https://developers.weixin.qq.com/community/develop/doc/0002488d90c160f8000dd134955c00
