### ISSUE TITLE
试了下example，BitmapText没显示出来？

### ISSUE THREAD

**Issue by KailZhang** [skyfish-qc/pixi-miniprogram#41]
如题，可能会是什么问题呢

**Comment by skyfish-qc** [comment]
看看是不是开了域名检测了

**Comment by KailZhang** [comment]
![WechatIMG4866](https://github.com/user-attachments/assets/85fe82ba-99c6-4402-be2c-b49f24034afb)
那不会，其他资源都能加载，也没有什么报错。上边这样的，spine和live2d我估计用不着注释掉了
感谢作者回复

**Comment by KailZhang** [comment]
![WechatIMG4866](https://github.com/user-attachments/assets/85fe82ba-99c6-4402-be2c-b49f24034afb)
那不会，其他资源都能加载，也没有什么报错。上边这样的，spine和live2d我估计用不着注释掉了
@skyfish-qc 感谢作者回复

**Comment by skyfish-qc** [comment]
哦，那个fontSize在v7版本需要设置数字，你改成60就可以了

**Comment by KailZhang** [comment]
OK.THX
