### ISSUE TITLE
使用UniAPP+vue3+PIXI-MINI的时候，引入createPIXI报错 提示 "createPIXI" is not exported by "src/libs/pixi.miniprogram.js", imported by "src/pages/pixi/pixi.vue"

### ISSUE THREAD

**Issue by a243065157** [skyfish-qc/pixi-miniprogram#42]
```
import { createPIXI } from '../../libs/pixi.miniprogram';
  import { onMounted, ref, reactive, nextTick, getCurrentInstance } from 'vue';
  const init = () => {
    console.log('createPIXI', createPIXI);
  };
```
编辑器报错
` "createPIXI" is not exported by "src/libs/pixi.miniprogram.js", imported by "src/pages/pixi/pixi.vue".`
求指点

**Comment by a243065157** [comment]
uniapp版本 3.0.0-4010520240507001
pixi库已安装 7.3.2
使用dist和example里面的库都会报错

**Comment by skyfish-qc** [comment]
pixi库是打包在里面的，不需要额外安装的，但在uniapp上没测试过，这个需要测试一下

**Comment by skyfish-qc** [comment]
你可以给个简单的使用工程代码，这边检查一下

**Comment by a243065157** [comment]
https://github.com/a243065157/uni-piximini
用这个项目就可以了，使用import和require都会报错，
require的时候 微信开发者工具会报`Error: module 'libs/pixi-miniprogram.js' is not defined, require args is '../../libs/pixi-miniprogram'`

**Comment by a243065157** [comment]
问题解决了，不是库的问题，是开发者工具的问题，我把项目文件放到static目录下就可以正常使用Require引入了
